### ISSUE TITLE
Implement basic dev tileset

### ISSUE THREAD

**Issue by HazmatDrone** [HazDroneCorp/combat-engineers#1]
We need a tileset that gives us a bit of dimensionality to work with. Basically, in this sort of style:
![image](https://user-images.githubusercontent.com/69188984/103477155-df22ae00-4e0f-11eb-8bbe-f332e52bbe53.png)
For now, we only really need dev textures; quick and dirty and will be refined later.

Textures we need:
- [x] Grass
- [ ] Stone
  - [ ] Ore (floor tile)
- [ ] A shack (Just one that sits on top of the floor tileset
- [ ] Fences
- [ ] Trees

**Comment by HazmatDrone** [comment]
Tileset added in d7640c1
![Uploading image.png…]()

**Comment by HazmatDrone** [comment]
We want some buildings. Ideally they'd look like this in the overworld:
![image](https://user-images.githubusercontent.com/69188984/103480303-ab538280-4e27-11eb-9fb8-dc7481c56ba2.png)
When you enter them, the building itself becomes transparent to reveal the insides.
Also, you place them by drawing the rectangle they fill, and then drawing rectangles next to those to form rooms. E.g.:
![image](https://user-images.githubusercontent.com/69188984/103480301-a8589200-4e27-11eb-9e5b-ddedbaa34c1a.png)

**Comment by Krutonium** [comment]
Would it not be easier to have the buildings non-eucliean, like Stardew, and transition the player to a new map?

**Comment by HazmatDrone** [comment]
TBH, probably, yeah

For carriages on the train, this will be a must-have, as we can't make a train track that's 4 tiles wide without messing up our style, at least imo

For buildings, we can make them non-euclidian, but perhaps keep the same overall shape? E.g. have them scale by 2x. Since the buildings can be any shape or size, they will need to more or less uniformly scale if they're non-euclidian.

I think I need to outline *just how modular* I want building in this game to be.

**Comment by Krutonium** [comment]
>For buildings, we can make them non-euclidian, but perhaps keep the same overall shape? E.g. have them scale by 2x.

If you look at Pierres shop in SDV, or the Wizards hut/tower, neither one fits the footprint of the building even slightly - Pierres house/shop would fill the square, and the Wizards place is square.

**Comment by HazmatDrone** [comment]
![image](https://user-images.githubusercontent.com/69188984/103525604-96ccc400-4ed3-11eb-907b-37e5fc2ebc15.png)

**Comment by Krutonium** [comment]
Far Right = Junimo

**Comment by HazmatDrone** [comment]
Unassigning Glauca unless more new textures are needed for testing purposes.

**Comment by HazmatDrone** [comment]
Moving this off master branch because it's really annoying every time it messes with stuff
