### ISSUE TITLE
How do we graciously upscale our pixel art?

### ISSUE THREAD

**Issue by HazmatDrone** [HazDroneCorp/combat-engineers#24]
One option is to scale the very root scene up 2x, but this causes weird coordinate issues. The most prominent being that the global position of things must always be scaled down 2x again when moving things around. I think this is something we should do with viewports?

**Comment by HazmatDrone** [comment]
@Krutonium

**Comment by Krutonium** [comment]
Um, I *think* you would do this with Viewports yeah

**Comment by HazmatDrone** [comment]
Fixed in 26c93effe4e00f232027203e226b80f033d0f995
