### ISSUE TITLE
Tie console, UI, etc to the playercharacter

### ISSUE THREAD

**Issue by HazmatDrone** [HazDroneCorp/combat-engineers#54]
Make sure that if I simply drag and drop the player into any scene and try to launch that scene, the basic stuff and things will be functional, e.g. console, UI, etc

(Also, if the player character is not needed, they can just be hidden with physics disabled.)

**Comment by Krutonium** [comment]
NTS: Make Search Relative within Node

**Comment by Krutonium** [comment]
Can you post the exact error you saw?

**Comment by HazmatDrone** [comment]
```
E 0:00:00.520   get_node: Node not found: ../UI/CanvasLayer/Console.
  <C++ Error>   Condition "!node" is true. Returned: __null
  <C++ Source>  scene/main/node.cpp:1381 @ get_node()
  <Stack Trace> :0 @ Godot.Node Godot.NativeCalls.godot_icall_1_571(IntPtr , IntPtr , IntPtr )()
                Node.cs:617 @ Godot.Node Godot.Node.GetNode(Godot.NodePath )()
                PlayerCharacter.cs:78 @ void PlayerCharacter._Ready()()
E 0:00:00.527   void PlayerCharacter._Ready(): System.NullReferenceException: Object reference not set to an instance of an object.
  <C++ Error>   Unhandled exception
  <C++ Source>  /home/resin/.nextcloud/Documents/projects/combat-engineers/gamecharacters/Player/PlayerCharacter.cs:79 @ void PlayerCharacter._Ready()()
  <Stack Trace> PlayerCharacter.cs:79 @ void PlayerCharacter._Ready()()
```

**Comment by HazmatDrone** [comment]
This can be fixed by making sure the UI and PlayerCharacter node are both in the scene, below the root node. However, it would be more sensible if the UI was part of the Player, and was relative, so that the PlayerCharacter can simply be placed anywhere without anything breaking.

**Comment by Krutonium** [comment]
Making it relative means it can be attached to anything, and still work, not just the player.

**Comment by HazmatDrone** [comment]
The issue is that the player seems to currently depend on the existence of the console. You can't make a scene with the player without the UI.

**Comment by Krutonium** [comment]
Wait why is the playercharacter looking for the console?

**Comment by HazmatDrone** [comment]
I dunno, you tell me
