### ISSUE TITLE
Move script template dir so I can tab-complete faster

### ISSUE THREAD

**Issue by SuscipiamSingularitatem** [HazDroneCorp/combat-engineers#72]
also @HazmatDrone you checked in files made with the stock template instead so I assume you haven't set something correctly

**Comment by HazmatDrone** [comment]
Consider trying `zsh` tab completion.

Also, consider [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh) with the `z` plugin [enabled](https://github.com/ohmyzsh/ohmyzsh#enabling-plugins).
